<a href="https://colab.research.google.com/github/colnagoc64/python_db/blob/master/day01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
from google.colab import drive

In [8]:
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np

In [10]:
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/csv-data/01. CCTV_in_Seoul.csv')

In [11]:
df

기관명    소계  2013년도 이전  2014년  2015년  2016년
0    강남구  2780       1292    430    584    932
1    강동구   773        379     99    155    377
2    강북구   748        369    120    138    204
3    강서구   884        388    258    184     81
4    관악구  1496        846    260    390    613
5    광진구   707        573     78     53    174
6    구로구  1561       1142    173    246    323
7    금천구  1015        674     51    269    354
8    노원구  1265        542     57    451    516
9    도봉구   485        238    159     42    386
10  동대문구  1294       1070     23    198    579
11   동작구  1091        544    341    103    314
12   마포구   574        314    118    169    379
13  서대문구   962        844     50     68    292
14   서초구  1930       1406    157    336    398
15   성동구  1062        730     91    241    265
16   성북구  1464       1009     78    360    204
17   송파구   618        529     21     68    463
18   양천구  2034       1843    142     30    467
19  영등포구   904        495    214    195    373
20   용산구  1624       1368    218    112    398
21   은평구  1873       1138    224    278    468
22   종로구  1002        464    314    211    630
23    중구   671        413    190     72    348
24   중랑구   660        509    121    177    109

In [15]:
df=pd.DataFrame({'name':['hong','park'],'age':[10,20]})

In [16]:
df

name  age
0  hong   10
1  park   20

In [17]:
df.index

RangeIndex(start=0, stop=2, step=1)

In [18]:
df.name

0    hong
1    park
Name: name, dtype: object

In [19]:
df.name.index 
#rangelndex 데이터타입이 class (부품) 그래서 다른 방식으로 쓰고싶으면 타입을 바꿔줘야한다

RangeIndex(start=0, stop=2, step=1)

In [21]:
df.name.values #값들은 array

array(['hong', 'park'], dtype=object)

In [22]:
values_list=df.name.values.tolist() # array을 list로 바뀌는코드

In [23]:
values_list

['hong', 'park']

In [38]:
df2= pd.DataFrame(data=[['hong',10],['park',20]],columns=['name','age'])
df2

name  age
0  hong   10
1  park   20

In [39]:
df2.dtypes

name    object
age      int64
dtype: object

In [40]:
df2['age'].astype(float) # 원본을 바꾸지않는 비파괴 함수

0    10.0
1    20.0
Name: age, dtype: float64

In [41]:
df2.dtypes

name    object
age      int64
dtype: object

In [42]:
df2['age']=df2['age'].astype(float) #원본을 바꾸는 함수 

In [43]:
df2.dtypes

name     object
age     float64
dtype: object

In [44]:
df2['age']=df2['age'].astype(int)

In [45]:
df2.dtypes

name    object
age      int64
dtype: object

In [46]:
df2.describe() # 숫자형만 나타내준다.

age
count   2.000000
mean   15.000000
std     7.071068
min    10.000000
25%    12.500000
50%    15.000000
75%    17.500000
max    20.000000

In [47]:
type(df2['name'])

pandas.core.series.Series

In [48]:
df2['name']

0    hong
1    park
Name: name, dtype: object

In [49]:
df2['name'].index

RangeIndex(start=0, stop=2, step=1)

In [50]:
df2['name'].values

array(['hong', 'park'], dtype=object)

In [51]:
type(df2['name'].values)

numpy.ndarray

In [52]:
mask2=np.zeros((3,4))
mask2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [56]:
arr2=np.array([
    [1,2,3],
    [4,5,6]
], dtype=np.float64)
arr2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [57]:
arr3=np.array([
    [7,9,8],
    [10,11,12]
], dtype=np.float64)
arr3

array([[ 7.,  9.,  8.],
       [10., 11., 12.]])

In [58]:
arr2+arr3

array([[ 8., 11., 11.],
       [14., 16., 18.]])

In [59]:
arr2 * arr3

array([[ 7., 18., 24.],
       [40., 55., 72.]])